

# This file was *autogenerated* from the file sw/otbn/crypto/rsa/rsa.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_2048 = Integer(2048); _sage_const_256 = Integer(256); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10)

# a = randint(0, 2^4352 - 1)

# x = randint(0, 2^256 - 1)
# y = randint(0, 2^4096 - 1)
# z = x * y + a

# print(z.bit_length())
# # assert z.bit_length() <= 4352

# print("0x%0x" % (x))
# print("0x%0x" % (y))
# print("0x%0x" % (a))
# print()
# print("0x%0x" % (z))
# print()

set_random_seed(_sage_const_2 )

MOD_SIZE = _sage_const_2048 
PRIME_SIZE = MOD_SIZE // _sage_const_2 
WORD_SIZE = _sage_const_256 

p = random_prime(_sage_const_2 **PRIME_SIZE - _sage_const_1 , lbound=_sage_const_2 **(PRIME_SIZE-_sage_const_1 ))
q = random_prime(_sage_const_2 **PRIME_SIZE - _sage_const_1 , lbound=_sage_const_2 **(PRIME_SIZE-_sage_const_1 ))

n = p * q

mu = power_mod(-n, -_sage_const_1 , _sage_const_2 **WORD_SIZE)
r2 = power_mod(_sage_const_2 **MOD_SIZE, _sage_const_2 , n)

def mont(a, b):
    c = _sage_const_0 
    for i in range(MOD_SIZE // WORD_SIZE):
        ai = (a >> WORD_SIZE*i) % _sage_const_2 **WORD_SIZE
        c = c + ai * b
        d = (mu * c) % _sage_const_2 **WORD_SIZE
        c = (c + d * n) >> WORD_SIZE
    # if c >= 2^MOD_SIZE:
    #     c -= n
    if c >= n:
        print("fsaf")
        c -= n
    return c


# good = False
# i = 0
# while True:

a = randint(_sage_const_0 , _sage_const_2 **(MOD_SIZE) - _sage_const_1 )
b = randint(_sage_const_0 , _sage_const_2 **(MOD_SIZE) - _sage_const_1 )
c = mont(a, b)

print("0x%0x" % (a))
print("0x%0x" % (b))
print("0x%0x" % (n))
print("0x%0x" % (mu))
print("0x%0x" % (c))
print(n.bit_length())


ci = (a * b) % n
#assert c == ci

w = _sage_const_10 
c0 = _sage_const_2 **(MOD_SIZE-w)

its = MOD_SIZE + w

for i in range(its):
    c0 = (c0 + c0) % n

print()
print("0x%0x" % r2)
print("0x%0x" % c0)
assert r2 == c0

